import Head from "next/head"
import Hero from "../components/Hero"

export default function Home() {
	return (
		<>
			<Head>
				<title>Milica Janevski - Pozorišna i filmska glumica</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero></Hero>
		</>
	)
}
